### ISSUE TITLE
Couldn't process file View\frmMain.resx

### ISSUE THREAD

**Issue by kungen32** [Cjaker/SpriteSheetMaker#1]
After a try to realese it, show up and error,

Severity	Code	Description	Project	File	Line	Suppression State
Error		Couldn't process file View\frmMain.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files.	SpriteSheetMaker

**Comment by Cjaker** [comment]
Check that: https://stackoverflow.com/a/58840644
